### ISSUE TITLE
Eshop firmware spoof not working anymore

### ISSUE THREAD

**Issue by Masamune3210** [smealum/HANS#11]
Went to buy a game, couldnt get firmware spoof to work any more. Doesnt matter wether i pick the eshop or the version that downloads old versions of games.

**Comment by Hartie95** [comment]
if you are on a firmware <=10.3, you could use a legit cia installer with memchunckhax2 and install the newest nver, to access the eshop.
To get it, simply use 3dnus and use the title id and version from the 3dbrew title list.

**Comment by Masamune3210** [comment]
Unfortunately I'm on 10.3.0.28. any other ideas?

**Comment by Hartie95** [comment]
On 10.4 memchunckhax2 got fixed, you should be able to use a legit cia installer.

**Comment by Masamune3210** [comment]
im running ironhax, could you possibly link a guide for memchunkhax2, quick google got me nowhere real fast

**Comment by Masamune3210** [comment]
found a cia installer, will updating nver without updating the firm harm anything?

**Comment by Hartie95** [comment]
Not that i know, but you could also download your current nver, so you could reonstall it if needed.

**Comment by Masamune3210** [comment]
Bit the bullet and downgraded to 9.2 so i could use emunand. thanks for the help
