### ISSUE TITLE
eShop Crash

### ISSUE THREAD

**Issue by szhrs** [smealum/HANS#12]
Selecting eShop in HANS through the HANS game-selection screen or with the "eShop" and "old version downloader" shortcuts crash before getting to the HANS settings. 
It just hangs with a black on top screen and yellow on bottom screen. 

Tested on:
Hax 2.5 with

-OLD 3DS (firmware 10.5.0.30 U)
-NEW 3DS (firmware 10.5.0.30 E)

**Comment by TuxSH** [comment]
Firmware 10.4.0-29 introduced a kind of _Address Space Layout Randomization_ (ASLR) for system apps, thus making HANS unable to patch these programs.
