### ISSUE TITLE
.code 

### ISSUE THREAD

**Issue by cl1ents** [smealum/HANS#13]
How do .code works ?
Tell me ...

**Comment by ghost** [comment]
Ah. They are code. What are you asking?

**Comment by cl1ents** [comment]
Like... How do You make codes and how to use it ? And maybe where do we get it

-----Message d'origine-----
De : "JP M" notifications@github.com
Envoyé : ‎04/‎03/‎2016 21:58
À : "smealum/HANS" HANS@noreply.github.com
Cc : "MRePotatoes" evan97401@gmail.com
Objet : Re: [HANS] .code  (#13)

Ah. They are code. What are you asking?

**Comment by tsubasamanda** [comment]
Well, .code is a segment of a game on the 3DS. It contains the assembled code for the game you are trying to play. It is possible to dump the code and modify it with a hex editor, so you can change how the game works, but this is quite difficult.

**Comment by cl1ents** [comment]
And where do i get some ?

**Comment by tsubasamanda** [comment]
The code is not related to cheat codes. You don't modify the raw RAM values (like gameshark or action replay), the current system is modifying the code. There aren't any available sources for these "codes".

**Comment by cl1ents** [comment]
So it is modifying Gameplay mechanics ?
If yes, That's what I want!

**Comment by profi200** [comment]
Dude, if you don't know what code is or how it works then please shut up and learn these things first instead of opening useless issues. Don't get me wrong, questions are ok but the best way is if you educate yourself about this. There are tons of resources on the internet.

**Comment by cl1ents** [comment]
WOW Just don't be rude ! Mmph
