### ISSUE TITLE
Unknown libctru, Missing unicode.tbl

### ISSUE THREAD

**Issue by Syphurith** [smealum/HANS#2]
The loader code would ask for `ctr/GX.h`. And this file isn't from normal libctru, but rather from a ctrsdk version. However since ctrsdk is now obselete you can't even find it on github. Thus it can't be built.
HANS main folder could not be built cause of lacking the `unicode.tbl`. It is said to require `darm` to work. So after compiled it i crafted a installation of it. However no `unicode.tbl` stopped me.

**Comment by smealum** [comment]
what the hell is ctrsdk ?

loader just uses and old version of ctrulib. the same as the one ninjhax uses should be fine..

i'll push unicode.tbl when i can but i think you can also find that on the ninjhax repo if you want

**Comment by Syphurith** [comment]
@smealum Thanks for reply. I would try to build it then. Once done, i would close this myself.
Orz in main.c,. `loader_bin.h` isn't found.
Cause darm offers no way to install it I copied all its .h to include and its .a to lib....
And.. the `loader_bin`.. **Fixed with manually execute `make build/stub.bin.o`**. So makefile failed..
_Sorry to mention but the build script is really a mess for others now.. Unlucky i can't fix it myself._
Whatever.. Would wait for you to show up with new files it lacks now.

Inside `Loader`
**`stub_bin_size`**
After execute `make build/stub.bin.o` manually the bin get copied and translated, it would build then.
**Legacy libcrtu.** [This version](https://github.com/smealum/ctrulib/tree/c4382042d633168019137580aaa5bef1eaa7d103)
For use with legacy libctru you need set `CTRULIB`. Luckily main part doesn't require legacy one.

Main
**build**
First just try to run the build.bat. ugly but working - even not to its end all that easy.
**`darm` Compilation**
You need to modify the Makefile of darm to let it be as such:

```
AR = arm-none-eabi-ar
CC = arm-none-eabi-gcc
ARCH    :=  -march=armv6k -mtune=mpcore -mfloat-abi=hard
CFLAGS  :=  -std=c11 -g -Wall -O2 -mword-relocations -fomit-frame-pointer -ffast-math $(ARCH)
CFLAGS  +=  $(INCLUDE) -DARM11 -D_3DS
```

Simply this is almost copied from HANS Makefile, except the `-std=c11`.
**`darm` Installation**
darm offers no installation script, thus you don't know where to put those.
DevKitPro would search its own directory for the darm.a, so put the libdarm.with original libctru.a.
And all those header files from darm, into the `include` folder with `common.h`.

And finally get all built. OK it is solved for me now.

**Comment by Syphurith** [comment]
Thanks for offering the source, _even the Makefile is now a mess. And those libraries.._
Unfortunately i can not write graceful Makefile.. Sorry for that. I would close this.
